### ISSUE TITLE
make: *** No rule to make target 'install'.  Stop.

### ISSUE THREAD

**Issue by razr** [conan-io/hello#4]
and then install does not exist for this example

```bash
user@host:~/github/conan-io/hello/build$ make install
make: *** No rule to make target 'install'.  Stop.
```

**Comment by memsharded** [comment]
Hi @razr 

This doesn't contain enough information. Please submit full reports including:
- All the files necessary to reproduce
- The exact commands to reproduce
- The full output of the commands
- The Conan version and system details

**Comment by razr** [comment]
I have tried to build it with cmake (no conan), just to see what artifacts this project produces and installs. It was not clear from the README, and my conan build gave me a warning:

```bash
hello/0.1: Build folder /home/user/.conan2/p/b/hellodf60b8bc1cac6/b
hello/0.1: Generating the package
hello/0.1: Packaging in folder /home/user/.conan2/p/b/hellodf60b8bc1cac6/p
hello/0.1: Calling package()
hello/0.1: package(): WARN: No files in this package!
```

So I have decided to build and install this project as

```bash
git clone https://github.com/conan-io/hello.git
mkdir hello/build && cd hello/build
cmake ..
make
make install
 ```

**Comment by memsharded** [comment]
Sorry, I am very confused now.

I have realized this repo seems the legacy, old one. You can see in it that it was already updated to CMake 3.15 there: https://github.com/conan-io/libhello/blob/main/CMakeLists.txt

The new, maintained and actually used in the docs is https://github.com/conan-io/libhello

You shouldn't find any link to this repo in the docs anymore, just one occurence, but not as part of the tutorials or any reproducible example.

**Comment by razr** [comment]
thanks for the clarification. I picked the old one. Sorry for confusion

**Comment by memsharded** [comment]
No prob, thanks for the report anyway!

I have added a note in the readme and we will soon archive the repo.

**Comment by razr** [comment]
@memsharded the project you have mentioned is a library. What example shall be used to produce a binary? Otherwise, how can I test the artifacts?

**Comment by memsharded** [comment]
Not sure what you mean.
The main entry point for these repos should be the conan docs in https://docs.conan.io

Depending on what you are trying to achieve. If you want to create a default project for an application executable with CMake then the template:

```
conan new cmake_exe -d name=myapp -d version=0.1
```
would be a good starting point. 
Note this is almost the same as the Getting Started Tutorial about creating packages in https://docs.conan.io/2/tutorial/creating_packages/create_your_first_package.html, just changing ``cmake_lib`` -> ``cmake_exe``, because the package creation flow is basically the same.

**Comment by razr** [comment]
ah, I didn't know that. Thank you. Yes, I want to create an executable with CMake. Let me try this one.

**Comment by razr** [comment]
@memsharded I have tried to build `myapp`  following your advice. OS is VxWorks, so I have this profile:

```text
[settings]
os=VxWorks
os.version=7
arch=x86_64
compiler=wr-cc

# Adjust to the clang version of VxWorks llvm package
compiler.version=17
compiler.libcxx=libcplusplus
compiler.threads=None
build_type=Release

[buildenv]
CONAN_CMAKE_TOOLCHAIN_FILE=$WIND_CC_SYSROOT/mk/toolchain.cmake
CHOST=wr
AR=wr-ar
AS=wr-as
RANLIB=wr-ranlib
CC=wr-cc
CXX=wr-c++
STRIP=wr-strip
```

Previously it took the toolchain file provided by VxWorks. But in Conan 2 it seems this env var does not exist, and the build process takes `conan_toolchain.cmake` instead.

```bash
myapp/0.1: Running CMake.configure()
myapp/0.1: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/user/.conan2/p/b/myappe675d78283366/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/user/.conan2/p/b/myappe675d78283366/b"
-- Using Conan toolchain: /home/user/.conan2/p/b/myappe675d78283366/b/build/Release/generators/conan_toolchain.cmake
-- The CXX compiler identification is Clang 17.0.6
System is unknown to cmake, create:
Platform/VxWorks to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
-- Detecting CXX compiler ABI info
System is unknown to cmake, create:
Platform/VxWorks to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: ~/Downloads/wrsdk/host/x86_64-linux/bin/wr-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/user/.conan2/p/b/myappe675d78283366/b/build/Release
```

How can I pass VxWorks toolchain to the Conan 2 build? I run it as

```bash
conan new cmake_exe -d name=myapp -d version=0.1
conan create . -pr=../.conan2/profiles/vxworks-profile
```

**Comment by memsharded** [comment]
I am not sure about a few things, I am missing details.

About the profile, there are many settings that don't exist in the default profile, for example ``compiler.libcxx=libcplusplus`` is generally incorrect, the defaults have ``libc++`` or ``libstdc++`` or ``libstdc++11``. Same with ``compiler=wr-cc``

Then, ``CONAN_CMAKE_TOOLCHAIN_FILE`` doesn't exist in Conan 2, it was just in Conan 1. Please make sure to check the Conan 2 documents when using Conan 2.

In this case, most env-vars for configuration have been replaced by ``conf`` items. Check ``conan config list`` for them or read about them in the docs:

- https://docs.conan.io/2/reference/config_files/profiles.html#conf
- https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#using-a-custom-toolchain-file

The one you are looking for is most likely ``tools.cmake.cmaketoolchain:user_toolchain``.

**Comment by razr** [comment]
thank you, I have added these two lines to my profile and they do the job

```bash
[conf]
tools.cmake.cmaketoolchain:user_toolchain=["$ENV{WIND_CC_SYSROOT}/mk/toolchain.cmake"]
```

```bash
[vxWorks *]# myapp
myapp/0.1: Hello World Debug!
  myapp/0.1: __x86_64__ defined
  myapp/0.1: __cplusplus201402
  myapp/0.1: __GNUC__4
  myapp/0.1: __GNUC_MINOR__2
  myapp/0.1: __clang_major__17
myapp/0.1 test_package
```

Wind River uses compiler driver `wr-cc` which wraps around `clang` or `gcc` depending on the configuration.

```bash
$ wr-cc --version
clang version 17.0.6.1
Target: x86_64
Thread model: posix
```

and `libcplusplus` is the name of the C++ library used by VxWorks. 

```bash
ldd ~/.conan2/p/b/myappf4fec0baab459/p/bin/myapp
        linux-vdso.so.1 (0x00007fffb93dd000)
        libc.so.1 => not found
        libcplusplus.so.1 => not found
        libllvmcplus.so.1 => not found
```

So I have added it to the `settings.yml`

```bash
compiler:
    wr-cc:
        version: ["17"]
        threads: [None]
        libcxx: [libcplusplus]
```

**Comment by memsharded** [comment]
> So I have added it to the settings.yml

Sounds good. 
Happy that you manage to make it work. 

As some extra tip about custom settings, note that the built-in helpers and toolchains like ``CMakeToolchain`` or ``AutotoolsToolchain``, use the ``settings`` and convert known settings to the corresponding build-system variables. When defining custom settings, often these helpers will not manage to correctly map them, and using the external toolchains as ``user_toolchain`` might be necessary. But in the same way you had to do it for ``CMake``, if you have other dependencies using ``Meson`` or ``Autotools``, it might be necessary to make sure they also get the right flags.

Happy to help, don't hesitate to create new tickets (in the Conan repo) for any further question or issue you might have. Thanks for the feedback!
